### ISSUE TITLE
Leaking file descriptors

### ISSUE THREAD

**Issue by telmich** [telmich/cdist#326]
When running on many hosts, non parallel, this error is caused: @asteven you know about this already

INFO: redmine-staging.panter.biz: Generating code for __file/etc/iptables.d/established
Traceback (most recent call last):
  File "/home/cdist/cdist/cdist/exec/local.py", line 175, in run
    return subprocess.check_output(command, env=env).decode()
  File "/usr/lib/python3.2/subprocess.py", line 515, in check_output
    process = Popen(*popenargs, stdout=PIPE, **kwargs)
  File "/usr/lib/python3.2/subprocess.py", line 745, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.2/subprocess.py", line 1176, in _execute_child
    errpipe_read, errpipe_write = _create_pipe()
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdist/cdist/bin/../scripts/cdist", line 185, in <module>
    commandline()
  File "/home/cdist/cdist/bin/../scripts/cdist", line 154, in commandline
    args.func(args)
  File "/home/cdist/cdist/cdist/config.py", line 90, in commandline
    cls.onehost(host, args, parallel=False)
  File "/home/cdist/cdist/cdist/config.py", line 131, in onehost
    c.run()
  File "/home/cdist/cdist/cdist/config.py", line 157, in run
    self.iterate_until_finished()
  File "/home/cdist/cdist/cdist/config.py", line 209, in iterate_until_finished
    objects_changed = self.iterate_once()
  File "/home/cdist/cdist/cdist/config.py", line 194, in iterate_once
    self.object_run(cdist_object)
  File "/home/cdist/cdist/cdist/config.py", line 257, in object_run
    cdist_object.code_remote = self.code.run_gencode_remote(cdist_object)
  File "/home/cdist/cdist/cdist/core/code.py", line 117, in run_gencode_remote
    return self._run_gencode(cdist_object, 'remote')
  File "/home/cdist/cdist/cdist/core/code.py", line 109, in _run_gencode
    return self.local.run_script(script, env=env, return_output=True, message_prefix=message_prefix)
  File "/home/cdist/cdist/cdist/exec/local.py", line 194, in run_script
    return self.run(command=command, env=env, return_output=return_output, message_prefix=message_prefix)
  File "/home/cdist/cdist/cdist/exec/local.py", line 181, in run
    raise cdist.Error(" ".join(*args) + ": " + error.args[1])
NameError: global name 'args' is not defined

**Comment by telmich** [comment]
Closed long time ago :-)
